'use strict';
const $=id=>document.getElementById(id);
const DEBOUNCE_MS=600;
let languages=[],ready=false,busy=false,composing=false,revision=0,timer=null,wanted=false,nextAt=0;
async function json(url,body){const response=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});let data;try{data=await response.json();}catch{throw Error('The local server did not return JSON.');}if(!response.ok||data.error)throw Error(data.error||'Request failed (HTTP '+response.status+').');return data;}
function update(){const input=$('input').value;$('count').textContent=Array.from(input).length.toLocaleString('en-US')+' characters';$('translate').disabled=!ready||!input.trim()||composing;$('swap').disabled=!ready||$('source').value==='auto';const source=$('source').selectedOptions[0]?.textContent||'Detect language',target=$('target').selectedOptions[0]?.textContent||'English';$('route').textContent=source+($('target').value!=='en'&&$('source').value!=='en'&&$('source').value!==$('target').value?' → English':'')+' → '+target;$('intermediate').hidden=!$('pivot').checked;}
function queue(delay=DEBOUNCE_MS){revision++;clearTimeout(timer);timer=null;wanted=ready&&!composing&&!!$('input').value.trim();nextAt=performance.now()+delay;$('output').value='';$('english').textContent='';$('timing').textContent='';$('copy').disabled=true;update();if(wanted){$('message').textContent='Waiting for typing to pause…';timer=setTimeout(translate,delay);}else if(ready)$('message').textContent='Ready · translation starts automatically as you type.';}
async function translate(){clearTimeout(timer);timer=null;if(busy||!wanted||!ready||composing)return;wanted=false;busy=true;const currentRevision=revision,start=performance.now(),text=$('input').value,source=$('source').value,target=$('target').value,bridge=$('pivot').checked,targetName=$('target').selectedOptions[0].textContent;const current=()=>revision===currentRevision;try{let result;if(source!==target&&bridge&&target!=='en'&&source!=='en'){$('message').textContent='Translating to English…';const first=await json('/translate',{q:text,source,target:'en',format:'text'});if(!current())return;$('english').textContent=first.translatedText;$('message').textContent='Translating English to '+targetName+'…';result=await json('/translate',{q:first.translatedText,source:'en',target,format:'text'});}else{$('message').textContent='Translating locally…';result=await json('/translate',{q:text,source,target,format:'text'});}if(!current())return;$('output').value=result.translatedText;$('copy').disabled=!result.translatedText;$('timing').textContent=((performance.now()-start)/1000).toFixed(1)+' s';$('message').textContent='Translation complete · processed locally.';}catch(error){if(current())$('message').textContent=error.message+($('english').textContent?' The English intermediate is available below.':'');}finally{busy=false;update();if(wanted&&!composing){clearTimeout(timer);timer=setTimeout(translate,Math.max(0,nextAt-performance.now()));}}}
$('translate').onclick=()=>queue(0);
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('output').value);$('message').textContent='Translation copied.';}catch{$('output').focus();$('output').select();$('message').textContent='Press Ctrl+C to copy the selected translation.';}};
$('clear').onclick=()=>{$('input').value='';queue();};
$('swap').onclick=()=>{if($('source').value==='auto')return;const source=$('source').value;$('source').value=$('target').value;$('target').value=source;queue();};
$('input').addEventListener('compositionstart',()=>{composing=true;queue();});
$('input').addEventListener('compositionend',()=>{composing=false;queue();});
$('input').addEventListener('input',event=>{if(!event.isComposing&&!composing)queue();else update();});
for(const id of ['source','target','pivot'])$(id).addEventListener('change',()=>queue());
(async()=>{try{const state=await json('/studio/status');languages=await json('/languages');for(const language of languages){$('source').add(new Option(language.name,language.code));if(language.code!=='en')$('target').add(new Option(language.name,language.code));}$('languages').textContent=languages.map(l=>l.name).join(' · ');ready=state.ready;if(ready)queue();else{$('message').textContent='Model installation is incomplete. Open Models for setup instructions.';update();}}catch(error){$('message').textContent=error.message;}})();
