'use strict';
const $=id=>document.getElementById(id),token=$('management').dataset.token;
let collection=null,pendingRemoval=null,busy=false,pollTimer=null;
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(data.error||'The model operation failed.');return data;}
function cell(row,value){const td=document.createElement('td');td.textContent=value;row.append(td);return td;}
function render(){if(!collection)return;const query=$('language-search').value.toLowerCase().trim(),rows=$('language-rows');rows.replaceChildren();const english=document.createElement('tr');cell(english,'English');cell(english,'en');cell(english,'Bridge');cell(english,'Bridge');cell(english,'Required');if(!query||'english en'.includes(query))rows.append(english);let count=0;for(const language of collection.languages){if(query&&!`${language.name} ${language.code}`.toLowerCase().includes(query))continue;count++;const row=document.createElement('tr');cell(row,language.name);cell(row,language.code);for(const installed of [language.toEnglish,language.fromEnglish]){const td=cell(row,'');const badge=document.createElement('span');badge.className='badge '+(installed?'ready':'missing');badge.textContent=installed?'Installed':language.configured?'Missing':'Available';td.append(badge);}const actions=cell(row,'');if(!language.configured||!language.toEnglish||!language.fromEnglish){const install=document.createElement('button');install.className='quiet';install.textContent=language.configured?'Repair':'Install';install.disabled=busy;install.setAttribute('aria-label',install.textContent+' '+language.name);install.onclick=()=>start('install',[language.code]);actions.append(install);}if(language.configured){const remove=document.createElement('button');remove.className='quiet danger-text';remove.textContent='Remove';remove.disabled=busy;remove.setAttribute('aria-label','Remove '+language.name);remove.onclick=()=>{pendingRemoval=language.code;$('remove-description').textContent=`Remove ${language.name} (${language.code}) from your local collection?`;$('remove-dialog').showModal();};actions.append(remove);}rows.append(row);}if(!count&&rows.children.length===0){const row=document.createElement('tr');cell(row,'No matching languages.').colSpan=5;rows.append(row);}$('language-count').textContent=`${count} matching languages · ${collection.languages.filter(l=>l.configured).length+1} configured including English`;$('model-count').textContent=`${collection.state.modelCount} / ${collection.state.expectedModelCount}`;$('collection-status').textContent=collection.state.ready?'Ready':'Setup needed';$('refresh-catalog').disabled=busy;}
function showJob(job){busy=!!job&&['queued','running'].includes(job.status);if(!job)return;$('job-panel').hidden=false;$('job-message').textContent=job.message;$('job-panel').dataset.status=job.status;const progress=$('job-progress');progress.hidden=!busy;if(job.total){progress.max=job.total;progress.value=job.received;}else progress.removeAttribute('value');$('job-transfer').textContent=job.received?`${(job.received/1048576).toFixed(1)} MB`+(job.total?` / ${(job.total/1048576).toFixed(1)} MB`:''):'';$('job-log').textContent=(job.events||[]).map(e=>e.message).join('\n');}
async function load(){clearTimeout(pollTimer);try{collection=await api('/studio/models');showJob(collection.job);render();if(busy)pollTimer=setTimeout(load,1000);}catch(error){$('job-panel').hidden=false;$('job-message').textContent=error.message;if(busy)pollTimer=setTimeout(load,2000);}}
async function start(action,languages=[]){if(busy)return;showJob({status:'queued',message:'Starting operation…',events:[]});render();try{showJob(await api('/studio/models/jobs',{action,languages}));await load();}catch(error){busy=false;$('job-panel').hidden=false;$('job-message').textContent=error.message;render();}}
$('language-search').oninput=render;$('refresh-catalog').onclick=()=>start('refresh');$('remove-cancel').onclick=()=>{$('remove-dialog').close();pendingRemoval=null;};$('remove-confirm').onclick=()=>{const code=pendingRemoval;$('remove-dialog').close();pendingRemoval=null;if(code)start('remove',[code]);};load();
